'use client'

import { motion } from 'framer-motion'
import ScrollReveal from './ScrollReveal'

const capabilities = [
  {
    label: 'Quantum Algorithm Generation',
    description: 'AI writes Qiskit and cQASM circuits from natural language descriptions',
    status: 'live',
    color: '#00ff88',
  },
  {
    label: 'Automated Benchmarking',
    description: 'LLM-generated solutions tested against quantum computing problem sets',
    status: 'live',
    color: '#00ff88',
  },
  {
    label: 'Hardware Execution',
    description: 'Circuits generated by AI run on Quantum Inspire backends (Starmon-7, Tuna-5, Tuna-9)',
    status: 'live',
    color: '#00ff88',
  },
  {
    label: 'Hybrid Classical-Quantum',
    description: 'AI generates hybrid algorithms with execute() and finalize() hooks for QI platform',
    status: 'live',
    color: '#00ff88',
  },
  {
    label: 'Interactive Visualizations',
    description: 'Three.js quantum state visualizations built through AI-human collaboration',
    status: 'building',
    color: '#ff8c42',
  },
  {
    label: 'Natural Language Quantum',
    description: 'Describe what you want to compute. AI translates to quantum circuits and explains results.',
    status: 'next',
    color: '#8b5cf6',
  },
]

export default function VibecodingSection() {
  return (
    <div>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {capabilities.map((cap, i) => (
          <ScrollReveal key={cap.label} delay={i * 0.08}>
            <div className="group relative p-5 rounded-lg border border-[#1e293b] bg-[#0f1729]/50 hover:bg-[#111827]/80 transition-all duration-300">
              <div className="flex items-center gap-2 mb-3">
                <div
                  className="w-1.5 h-1.5 rounded-full"
                  style={{ backgroundColor: cap.color }}
                />
                <span
                  className="font-mono text-[10px] uppercase tracking-widest"
                  style={{ color: cap.color }}
                >
                  {cap.status}
                </span>
              </div>
              <h4 className="text-white text-sm font-medium mb-2">{cap.label}</h4>
              <p className="text-gray-500 text-xs leading-relaxed">{cap.description}</p>
            </div>
          </ScrollReveal>
        ))}
      </div>

      {/* Code snippet */}
      <ScrollReveal delay={0.3}>
        <div className="mt-10 rounded-xl border border-[#1e293b] bg-[#0d1117] overflow-hidden">
          <div className="flex items-center gap-2 px-4 py-2.5 border-b border-[#1e293b]">
            <div className="w-2.5 h-2.5 rounded-full bg-[#ff5f57]" />
            <div className="w-2.5 h-2.5 rounded-full bg-[#febc2e]" />
            <div className="w-2.5 h-2.5 rounded-full bg-[#28c840]" />
            <span className="ml-3 font-mono text-xs text-gray-500">quantum_vibecoding.py</span>
          </div>
          <pre className="p-5 text-sm leading-relaxed overflow-x-auto">
            <code>
              <span className="text-gray-500"># Human prompt: &quot;Create a Bell state and measure it&quot;</span>{'\n'}
              <span className="text-gray-500"># AI generates and executes:</span>{'\n\n'}
              <span className="text-[#ff7b72]">from</span> <span className="text-[#ffa657]">qiskit</span> <span className="text-[#ff7b72]">import</span> <span className="text-white">QuantumCircuit</span>{'\n'}
              <span className="text-[#ff7b72]">from</span> <span className="text-[#ffa657]">qiskit_aer</span> <span className="text-[#ff7b72]">import</span> <span className="text-white">AerSimulator</span>{'\n\n'}
              <span className="text-white">qc</span> <span className="text-[#ff7b72]">=</span> <span className="text-white">QuantumCircuit(</span><span className="text-[#79c0ff]">2</span><span className="text-white">, </span><span className="text-[#79c0ff]">2</span><span className="text-white">)</span>{'\n'}
              <span className="text-white">qc.h(</span><span className="text-[#79c0ff]">0</span><span className="text-white">)</span>          <span className="text-gray-500"># Superposition</span>{'\n'}
              <span className="text-white">qc.cx(</span><span className="text-[#79c0ff]">0</span><span className="text-white">, </span><span className="text-[#79c0ff]">1</span><span className="text-white">)</span>      <span className="text-gray-500"># Entanglement</span>{'\n'}
              <span className="text-white">qc.measure([</span><span className="text-[#79c0ff]">0</span><span className="text-white">, </span><span className="text-[#79c0ff]">1</span><span className="text-white">], [</span><span className="text-[#79c0ff]">0</span><span className="text-white">, </span><span className="text-[#79c0ff]">1</span><span className="text-white">])</span>{'\n\n'}
              <span className="text-white">result</span> <span className="text-[#ff7b72]">=</span> <span className="text-white">AerSimulator().run(qc).result()</span>{'\n'}
              <span className="text-gray-500"># {'{'}&#39;00&#39;: 512, &#39;11&#39;: 512{'}'} — perfectly entangled</span>
            </code>
          </pre>
        </div>
      </ScrollReveal>
    </div>
  )
}
