'use client'

import { useInView, C } from '../lib/helpers'
import { FRAMEWORK } from '../data/framework'

export default function ConceptualFramework() {
  const { ref, visible } = useInView(0.1)
  return (
    <div ref={ref} className="px-4 sm:px-6 py-20">
      <div className={`max-w-3xl mx-auto transition-all duration-1000 ${visible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-12'}`}>
        <h2 className="text-2xl font-bold text-gray-200 mb-2">Poetic Devices as Quantum Operations</h2>
        <p className="text-sm text-gray-500 mb-10">
          Poets have always done what quantum computers do: hold contradictions, bind distant things, make the act of observation part of the meaning. The mapping below isn&apos;t a metaphor. It&apos;s a dictionary.
        </p>

        <div className="space-y-0">
          {FRAMEWORK.map((row, i) => (
            <div key={i} className="grid grid-cols-[1fr_1fr_2fr] sm:grid-cols-[140px_180px_1fr] gap-3 sm:gap-4 py-3 border-b border-[#111827]">
              <span className="text-sm font-medium text-gray-300">{row.device}</span>
              <span className="text-sm font-mono" style={{ color: C.blue }}>{row.gate}</span>
              <span className="text-sm text-gray-500">{row.why}</span>
            </div>
          ))}
        </div>

        {/* Worked examples */}
        <div className="mt-16 space-y-12">
          <h3 className="text-lg font-semibold text-gray-300">Three examples</h3>

          {/* Example 1: Superposition / Ambiguity */}
          <div className="border-l-2 pl-5 py-1" style={{ borderColor: C.ghz + '50' }}>
            <p className="text-xs font-mono mb-3" style={{ color: C.ghz }}>Superposition &rarr; Ambiguity</p>
            <p className="text-lg font-light italic text-gray-300 mb-4">
              &ldquo;I left the bank at closing time&rdquo;
            </p>
            <p className="text-sm text-gray-500 mb-3">
              This line is in superposition. It means two things at once &mdash; the river bank
              and the financial bank &mdash; and you hold both readings simultaneously until
              something later in the poem forces you to choose. That&apos;s collapse.
            </p>
            <p className="text-sm text-gray-500">
              On a quantum computer, this is a qubit in the state |0&#x27E9; + |1&#x27E9;. Both
              values are real and present. Measurement gives you one.
              Good poets keep you in superposition as long as possible.
            </p>
          </div>

          {/* Example 2: Entanglement / Rhyme */}
          <div className="border-l-2 pl-5 py-1" style={{ borderColor: C.blue + '50' }}>
            <p className="text-xs font-mono mb-3" style={{ color: C.blue }}>Entanglement &rarr; Rhyme</p>
            <div className="space-y-1 mb-4">
              <p className="text-lg font-light italic" style={{ color: C.blue }}>
                When you are here the touch runs warm against the walls
              </p>
              <p className="text-lg font-light italic" style={{ color: C.blue + 'cc' }}>
                the quiet evening finds its way slowly home
              </p>
            </div>
            <p className="text-sm text-gray-500 mb-3">
              This couplet was generated by two entangled qubits. Each qubit independently
              chose between &ldquo;you/your ghost&rdquo; &mdash; but because they were entangled, when one said
              &ldquo;you&rdquo;, its partner was guaranteed to say &ldquo;warm&rdquo;.
              The two lines are correlated without either one &ldquo;causing&rdquo; the other.
            </p>
            <p className="text-sm text-gray-500">
              Rhyme works the same way. &ldquo;Walls&rdquo; at the end of line one doesn&apos;t cause &ldquo;home&rdquo; at the
              end of line two &mdash; but once you hear one, the other becomes inevitable. The
              correlation between distant words is the poem&apos;s structure.
            </p>
          </div>

          {/* Example 3: Delayed measurement / Enjambment */}
          <div className="border-l-2 pl-5 py-1" style={{ borderColor: C.presence + '50' }}>
            <p className="text-xs font-mono mb-3" style={{ color: C.presence }}>Delayed measurement &rarr; Enjambment</p>
            <div className="mb-4">
              <p className="text-lg font-light italic text-gray-300">
                the room holds nothing but us
              </p>
              <p className="text-lg font-light italic" style={{ color: C.presence }}>
                the door stays open
              </p>
            </div>
            <p className="text-sm text-gray-500 mb-3">
              At the end of the first line, &ldquo;nothing but us&rdquo; is in superposition &mdash; the nothing of
              emptiness? Of sufficiency? Of isolation? The line break is a moment of suspension.
              You hold the ambiguity across the white space.
              Then &ldquo;the door stays open&rdquo; collapses it: the nothing is fullness, the room holds
              everything that matters, and the door is an invitation.
            </p>
            <p className="text-sm text-gray-500">
              This is delayed measurement. The qubit is prepared, but we wait to measure it.
              In the gap, the superposition is real. The next line is the measurement that
              resolves it into a definite meaning.
            </p>
          </div>
        </div>
      </div>
    </div>
  )
}
